URL_SERVICE = "https://cnt-a0385fc9-31cc-429b-b384-b4661fabbdae.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users"
CREATE_KITS_PATH = "/api/v1/kits"