URL_SERVICE = "https://cnt-ebe33966-9fd5-40a2-8f9f-8de8ec5cec50.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users"
CREATE_KITS_PATH = "/api/v1/kits"