URL_SERVICE = "https://cnt-647706d2-8c36-46bf-abae-855e8b540124.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users"
CREATE_KITS_PATH = "/api/v1/kits"